import random

#WINDOW SIZE
#-----------
WINDOW_H = 850
WINDOW_W = 1550
#-----------

#PLAYER STATS
#------------
PLAYER_MOVE_SPEED = 5
PLAYER_DMG = 20
PLAYER_HP = 150
#------------


#ENVIRONMENT STATS
#----------
#1. big tree
BIG_TREE_H = 128
BIG_TREE_W = 96

#2. small tree
SMALL_TREE_H = int(BIG_TREE_H/2)
SMALL_TREE_W = int(BIG_TREE_W/2)+20

#3. big rock
BIG_ROCK_H = 70
BIG_ROCK_W = 70

#4. small rock
SMALL_ROCK_H = int(BIG_ROCK_H/2)
SMALL_ROCK_W = int(BIG_ROCK_W/2)
#----------

#MONSTER STATS
#--------------
MONSTER_H = 50
MONSTER_W = 50
MONSTER_SPEED = 2
MONSTER_DMG = 20
MONSTER_HP = 100

# 1. orc
ORC_H = int(MONSTER_H*1.2)
ORC_W = int(MONSTER_W*1.2)
ORC_SPEED = int(MONSTER_SPEED*0.5)
ORC_DMG = int(MONSTER_DMG*1.4)
ORC_HP = int(MONSTER_HP*1.25)

# 2. goblin
GOBLIN_H = int(MONSTER_H*0.8)
GOBLIN_W = int(MONSTER_W*0.8)
GOBLIN_SPEED = int(MONSTER_SPEED*1.5)
GOBLIN_DMG = int(MONSTER_DMG*1.25)
GOBLIN_HP = int(MONSTER_HP*0.6)
#--------------


#PASSIVE MOBS STATS
PIG_H = 30
PIG_W = 30
PIG_SPEED = 1
PIG_HP = 0
PIG_START_X = random.randint(0,WINDOW_W-PIG_W) 
PIG_DESTINATION_X = PIG_START_X + 50
PIG_START_Y = random.randint(0,WINDOW_H-PIG_H)
PIG_DESTINATION_Y = PIG_START_Y + 50

COW_H = 50
COW_W = 50
COW_SPEED = 5
COW_HP = 0
COW_START_X = random.randint(0,WINDOW_W-COW_W) 
COW_DESTINATION_X = COW_START_X + 100
COW_START_Y = random.randint(0,WINDOW_H-COW_H)
COW_DESTINATION_Y = COW_START_Y + 100
